config/routes.rb
Giftshop::Application.routes.draw do

  post 'phukienso_products/clone' => 'phukienso_products#clone'

  resources :articles

  resources :statics

  resources :instructions
  match "/admin/reports/sales_detail" => "spree/admin/reports#sales_detail"
  match '/admin/products/:id/resume' => 'spree/admin/products#resume'
  mount Spree::Core::Engine, :at => '/'

  namespace :admin do
    resources :articles
    resources :announcements
    resources :instructions
    resources :barcodes
  end

  
  
  resources :products do
    resources :comments
  end
  
  namespace :spree do
    resources :line_items
  end

  Spree::Core::Engine.routes.append do
    resources :users do
      collection do
        get :download_shared_file
      end
    end
    namespace :admin do
      resources :share_files
      resources :settings
    end
  end
  
  
  

end

app/views/spree/admin/variants/_form.html.erb
<div data-hook="admin_variant_form_fields">
  <div class="clearfix">
    <div class="left" data-hook="variants">

      <% @product.options.each do |option| %>
        <p data-hook="presentation">
          <%= label :new_variant, option.option_type.presentation %><br />
          <% if @variant.new_record? %>
            <%= select(:new_variant, option.option_type.presentation,
              option.option_type.option_values.collect {|ov| [ ov.presentation, ov.id ] },
              {})
            %>
          <% else %>
            <% opt = @variant.option_values.detect {|o| o.option_type == option.option_type }.presentation %>
            <%= text_field(:new_variant,  option.option_type.presentation, :value => opt, :disabled => 'disabled') %>
          <% end %>
        </p>
      <% end %>

      <p data-hook="sku"><%= f.label :sku, t(:sku) %><br />
      <%= f.text_field :sku %></p>

      <p data-hook="price"><%= f.label :price, t(:price) %>:<br />
      <%= f.text_field :price, :value => number_to_currency(@variant.price, :unit => '') %></p>

      <p data-hook="cost_price"><%= f.label :cost_price, t(:cost_price) %>:<br />
      <%= f.text_field :cost_price, :value => number_to_currency(@variant.cost_price, :unit => '') %></p>

    <% if Spree::Config[:track_inventory_levels] && current_user.has_spree_role?("admin") %>
      <p data-hook="on_hand"><%= f.label :on_hand, t(:on_hand) %>: <br />
      <%= f.text_field :on_hand %></p>
    <% end %>
  </div>

  <div class="right" data-hook="admin_variant_form_additional_fields">
    <% [:weight, :height, :width, :depth].each do |field| %>
      <p data-hook="<%= field %>"><%= f.label field, t(field) %>:<br />
      <% value = @variant.send(field) %>
      <%= f.text_field field, :value => value %></p>
    <% end %>
  </div>
</div>

app/views/spree/admin/variants/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Variants' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <div data-hook="admin_variant_edit_form">
    <%= render :partial => 'form', :locals => { :f => f } %>
  </div>

  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/variants/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Variants'} %>

<table class="index sortable" data-sortable-link="<%= update_positions_admin_product_variants_path(@product) %>">
  <tr data-hook="variants_header">
    <th><%= t(:options) %></th>
    <th><%= t(:price) %></th>
    <th><%= t(:sku) %></th>
    <th><%= t(:on_hand) %></th>
    <th><%= t(:in_process) %></th>
    <th><%= t(:barcode) %></th>
    <th><%= t(:action) %></th>
  </tr>
  <tbody>
  <% @variants.each do |variant| %>
    <!-- you can skip variant with no options: that's just the default variant that all products have -->
    <% next if variant.option_values.empty? %>
    <tr id="<%= spree_dom_id variant %>" <%= 'style="color:red;"' if variant.deleted? %> data-hook="variants_row">
      <td><span class="handle"></span> <%= variant.options_text %></td>
      <td><%= money variant.price %></td>
      <td><%= variant.sku %></td>
      <td><%= variant.on_hand %></td>
      <td><%= variant.in_process %></td>
      <td><%= link_to variant.id, main_app.admin_barcode_path(variant.id), {"class" => "btn"} %></td>
      <td valign="top">
        <%= link_to_edit(variant) unless variant.deleted? %>
        &nbsp;
        <%= link_to_delete(variant) unless variant.deleted? %>
      </td>
    </tr>
  <% end %>
  <% unless @product.has_variants? %>
    <tr><td colspan="9"><%= t(:none) %></td></tr>
  <% end %>
  </tbody>
</table>

<% if @product.empty_option_values? %>

  <p class='first_add_option_types' data-hook="first_add_option_types">
    <%= t(:to_add_variants_you_must_first_define) %>
    <%= link_to t(:option_types), admin_product_url(@product) %>
    <%= t(:and) %>
    <%= link_to t(:option_values), admin_option_types_url %>
  </p>

<% else %>

  <div id="new_variant" data-hook></div>

  <br />

  <p id="new_var_link" data-hook>

    <%= link_to icon('add') + ' ' + t(:new_variant), new_admin_product_variant_url(@product), :remote => :true, 'data-update' => 'new_variant', :class => 'iconlink new' %>

    &nbsp;|&nbsp;

    <%= link_to @deleted.blank? ? t(:show_deleted) : t(:show_active), admin_product_variants_url(@product, :deleted => @deleted.blank? ? "on" : "off") %>
  </p>

  <%= image_tag 'spinner.gif', :plugin => 'spree', :style => 'display:none;', :id => 'busy_indicator' %>
<% end %>

app/views/spree/admin/variants/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <fieldset data-hook="admin_variant_new_form">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/variants/new.js.erb
$("#new_variant").html('<%= escape_javascript(render :template => 'spree/admin/variants/new', :formats => [:html], :handlers => [:erb]) %>');
$("#new_var_link").hide();